name: Build website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ruby ruby-dev build-essential gem ruby-bundler libmagickcore-dev libmagickwand-dev
          sudo bundle install --gemfile=GemfileBuild
          sudo sed -i -e 's/[0-9]*[MG]iB/4GiB/g' /etc/ImageMagick-*/policy.xml
          sudo sed -i -e 's/[0-9]*[MG]B/4GiB/g' /etc/ImageMagick-*/policy.xml
          sudo cat /etc/ImageMagick-*/policy.xml
      - name: Build
        run: bundle exec jekyll build
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: Website
          path: _site/
